readme.md

Add myself to the list!

---

readme.md

Add Jonathan Suh [jonsuh.com/uses](https://jonsuh.com/uses).

Add Jonathan Suh

---

readme.md

Adding Dr. Abstract

---

readme.md

Hey @wesbos 
This is a great initiative. This will really help in get to know different people's work ethics and workflows. Hope to see myself up on the list.
Finger crossed!
Regards.

Add Amit Merchant

---

readme.md

Submitted a PR after seeing this 👇

Add kumar.now.sh/uses

---

readme.md

This update adds Jon Quach's uses URL to the main README.md

Add Jon Quach

---

readme.md

This adds Andrew Healey's /uses link to the readme.md.
Hi 👋, thank you for maintaining this list. I love hunting for new things.

Add Andrew Healey

---

readme.md

Add myself, hello from France 👋😊

Add Aurel Tyson

---

readme.md

Thanks for setting this up Wes. Such a great idea! I truly appreciate the ways you help build and support this community.

Added my uses link!

---

readme.md

Hello !
Thanks for this repo. 
A lot of pages are interesting and I hope mine too :)
Best regards,

Add Francois Rabanel /uses

---

readme.md

Looking forward to be a part of your list. 🏃

Added John Michael Ferraris uses link

---

readme.md

Added Oscar te Giffel

---

readme.md

Adding [leny.me/uses](https://leny.me/uses/) to the list.
Thanks, Wes!

Add leny.me/uses

---

readme.md

Hey neighbor, this is a great idea.
I'd love to add my setup to this list 💯

Add Khalil's swagger /uses page.

---

readme.md

As it says on the tin. Self-adding awesome.

Add Sheree Peña to readme.md

---

readme.md

👋 uses pages from Danny de Vries
https://www.dandevri.es/uses/

Add Danny de Vries uses

---

readme.md

I'm changing the domain of my website.
Thanks!

Fix Andrew Healey URL

---

readme.md

Made with Gatsby and served with Now. ❤️

Add my /uses page

---

readme.md

Adds https://speek.design/uses

Add Jonathan Speek

---

readme.md

I've kept the one higher on the list, it's 2 lines above.

Remove double entry for Tracy Osborn

---

readme.md

Added my `/uses` page !
[https://blog.keziahmoselle.fr/uses/](https://blog.keziahmoselle.fr/uses/)

feat: add keziahmoselle uses

---

readme.md

Add Adam Wathan

---

readme.md

ayyyyy spent a lot of time on this, so lets add 'er up, buttercup.

add Josh Manders

---

readme.md

https://www.davidosomething.com/uses

Add David O'Trakoun

---

data.js

Update data.js with Troy Forster

---

data.js

Add stefanzweifel.io/uses

---

data.js

Adrian Marin addition

---

data.js

Added Andrew McCombe / @euperia

---

src/data.js

Add Tim Dorr

---

src/components/Topics.js

Just removing the cursor pointer styling on the tags for each person - that don't function as buttons. Cheers.

Remove pointer style on non-interactive tags

---

src/data.js

Add @midudev to the data.js

---

readme.md

Add @midudev to the list

---

src/data.js

Please bare with me for all the small PRs 🙈

Fix country

---

migration.md
src/data.js

- fix missing comma (data.js had a syntax error)

Migrate Hugo Di Francesco

---

src/data.js

@wesbos This is super dope, thank you for making this!  You made me realize my page has been a /uses page all along :)
Built a while back with [jigsaw](https://jigsaw.tighten.co/) & Airtable as a backend for all of the skill ingredients. Build & deploys via netlify.

Add Ben Leivian 🍔

---

src/data.js

thank you for contributing so much to the community Wes Bos

add A list of /uses pages detailing developer setups by @calypsobronte

---

src/data.js

I'm adding my twitter so it is less clicks to get from this site to my twitter if people want to get to it.

Add twitter to my listing

---

src/data.js

Hey Wes, thanks for the repo! Here's a quick PR to add myself.

Add myself

---

src/components/Person.js

Fixes long links breaking the design with ellipsis

Make sure long links does not break the design

---

readme.md

Add Bezael to readme file

---

src/components/Person.js

Fix for the issue #206 
Before & After demo.

Overflowing links fixed.

---

readme.md

Am I the only french on this website?
I need to bring some bread 🥖and cheese 🧀to get them come here 🤣

Add Jérémy Mouzin

---

readme.md

Added myself, @topener on GitHub, Wraldpyk on Twitter/Twitch and other platforms :)

add Rene Pot

---

package.json

Just as a test for us :angel: No need to merge this if you'd rather stay on a stable version.

Upgrade to styled-components v5 beta

---

.github/workflows/populate-readme.yml
package.json
scripts/populate-readme.js
scripts/readme-template.md

example https://github.com/iamandrewluca/awesome-uses/actions
`"type": "module"` was added in `package.json` so node could use esm imports
Closes #155

feat: add action to generate readme.md from data.js

---

src/data.js

Added myself to the list. I am [Praveen Kumar Purushothaman](https://praveen.science/).

Added Praveen Kumar Purushothaman

---

.github/workflows/data-validate.yml
scripts/data-validate.js

feat: add action to validate data.js

---

src/data.js

Added my uses. Thanks alot Wes!!! You da Man!!!

Added john garrett uses

---

src/data.js

Add Pawel Grzybek

---

scripts/data-validate.js

Part of #306 check that URLs entered have something to do with "uses"

Allow only uses (or similar) URLs

---

scripts/data-validate.js
src/data.js

Fix more flakey sites + fake green data check

---

src/data.js

thanks for the cool site @wesbos 🔥

added phiilu.com/uses (@phiilu)

---

src/components/Person.js

would be better to make this source a remote image as a file node so gatsby-image can optimize it

Request 50px avatar from clearbit

---

src/data.js

Hello,
I've created my profile for your awesome website.

Adding myself

---

src/data.js

Adding myself, Silvestar Bistrović.

---

src/data.js

I have added myself to the list.
I did it in the middle because of the conflicts warning. Let me know if it is wrong.
Thanks! 🤘

Adding José Manuel Lucas

---

src/data.js

Updated https://github.com/wesbos/awesome-uses/pull/345

Add Michal Miszczyszyn

---

readme.md
src/data.js

Adding Bamuleseyo Gideon

---

src/data.js

Add Ava Gaiety Wroten

---

src/data.js

Add Tiffany White

---

src/data.js

Love this idea! Looking forward to watching it grow and hopefully helping out with this specific project!

Add Will Presley - update data.js

---

src/data.js

Add Benjamin Edenhuizen

---

src/data.js

I stumbled upon https://uses.tech/ and  was immediately triggered to create my own /uses!

Add GoodBytes

---

readme.md
src/data.js

Added Ibrahim Cesar

---

src/components/FavIcon.js
src/components/Person.js
src/components/header.js
src/components/image.js
src/context/FilterContext.js
src/util/stats.js

style: fix eslint issues

---

src/util/stats.js

fix(tags): increase tag count by 1

---

src/data.js

Added myself, Keith Wagner to the list

Added Keith Wagner (@kpwags) to data.js

---

src/data.js

Hi there!
I just want to add my [uses](https://jorgecalle.co/uses) page to this awesome project.

Add Jorge Calle

---

src/data.js

Add Amarpreet Singh

---

src/components/Person.js

This makes emoji look more beautiful.

feat: make user emoji non italic

---

.github/pull_request_template.md
pull_request_template.md

Adding a PR template, re https://github.com/wesbos/awesome-uses/issues/413.
Marked as draft for now in case anything else needs adding to it. **Here's an example:**
----
* Ensure you are linking to a /uses page
* Ensure your data is formatted in the same way as other entries
* Ensure this PR has a title in the following format
* ✅ Add Your Name
* ✅ Add @twitterusername
* ❌ Add myself
* ❌ Adding myself!
* ❌ Add Your Name @twitter @github
* Ensure the code submitted is formatted similarly to existing code
* Ensure variable, method, function, and component names are clear and concise
**Add your name to verify:** Sam Cross
Closes #413

feat: add Pull Request template

---

src/data.js

markhorsell

---

src/data.js

Update Mark Horsell twitter handle

---

src/data.js

added Renee de Kruijf

---

src/data.js

Add Wes Baker

---

src/data.js

Relates to #441 
`Javascript` -> `JavaScript` in tags (but not in descriptions...)
**Add your name to verify:** Hugo :+1:

style: Javascript -> JavaScript in tags

---

src/data.js

opened a new pull request with corrected JSON data
**Add your name to verify:** Joe Astuccio

Add @jastuccio

---

src/data.js

Add @mknepprath

---

src/data.js

add @didiercatz

---

src/data.js

Add Divjot Singh (@bogas04)

---

src/data.js

Add @armno

---

src/data.js

Add @sstenb_k

---

src/data.js

Add Ajay Karwal

---

src/data.js

Add @getanwar

---

src/data.js

Add @nanoxd

---

src/data.js

Add @hankchizljaw

---

src/data.js

Add @telmo

---

src/data.js

Add @solrevdev

---

src/data.js

Add @asurbernardo

---

src/data.js

added @davyhausser

---

.github/workflows/data-validate.yml
package-lock.json
package.json
scripts/data-validate.js
scripts/utils.js
src/data.js

Closes #478 
Todo:
~~- [ ] (maybe) try to take a screenshot~~ won't do, would need to take a screenshot of the site, upload it somewhere and leave a comment referencing it using markdown syntax.

feat: comment on PR with validation outcome

---

src/data.js

Add @rolisz

---

src/data.js

Add Michael Gale

---

src/components/header.js
src/pages/index.js

Potentially, closes #426 
- add "top" id to main `h1`
- add a fixed-position link to `#top`
* Ensure the code submitted is formatted similarly to existing code
* Ensure variable, method, function, and component names are clear and concise
**Add your name to verify:** Hugo

feat: add HTML-only back to top link

---

src/data.js

Thanks for the fun collection! 😊
**Add your name to verify:** Jake Jarvis

Add @jakejarvis

---

src/data.js

Add @qbunt

---

src/data.js

Adding @robertovg 💪

---

src/data.js

Add Chuck Munson

---

src/data.js

Add Aaron A.

---

src/data.js

Add Mohammad Dohadwala

---

src/data.js

Add Yannick Le Roux

---

src/data.js

Add @mat_almeida

---

src/data.js

- added one passionate dev to the list

Add @xbojch

---

src/data.js

Duncan McClean @damcclean

---

src/data.js

Add Bruno Brito to list

---

src/data.js

add @josefaidt

---

src/data.js

Add @chris_berry

---

.gitignore
src/data.js

Added Myself, Caleb Ukle, along with updating the .gitignore to include `.idea/` directory created by all JetBrains Editors
[@CU_Galaxy](https://twitter.com/CU_Galaxy)
[/uses page](https://calebukle.com/uses')
Thanks for making this great project!

Add @CU_Galaxy

---

src/data.js

Update Michael Hoffmann (@mokkapps) entry

---

src/data.js

Add Nich Secord

---

src/data.js

Add @_kejk

---

src/data.js

Add @dalefrench0

---

src/data.js

Add @Zoran_Panev

---

readme.md
src/data.js

This PR is after listening to Syntax episode today
Added uses section on my website. I dont have dedicated page as its a single page layout but you can see in the footer section stuff that I use including website techstack that it was made of.

Add @rikinpatel

---

src/data.js

Add Rene Gens Add @renegens

---

src/data.js

Adding Simranjit Singh

---

src/data.js

add @MakonCline

---

src/data.js

Add roy Tang

---

src/data.js

vinoth chellamuthu @ecevinoth

---

src/data.js

Add Marc Littlemore. Thanks. 🙌

Add Marc Littlemore

---

src/data.js

Add Gabriel Wilkes

---

src/data.js

Add @ahmed_ibrahhim

---

src/data.js

Add @0x12b

---

src/data.js

Added myself to the list

---

src/data.js

**Add your name to verify:** Josh Moore

Add Josh Moore

---

src/data.js

Add @boborchard

---

src/data.js

Add @SpencerAung

---

src/data.js

Add Jenna Pederson

---

src/data.js

Add @vonexplaino

---

src/data.js

**Add your name to verify:** Arturo
-->

Add @agzertuche

---

src/data.js

Add Bruno Paz

---

src/data.js

**Add your name to verify:** Matt Busche

Add @mrbusche

---

src/data.js

Add @talknerdytomee

---

src/data.js

Add Jordi Hoven

---

src/data.js

Add Martin Chammah

---

src/data.js

Add Jibin Thomas

---

src/data.js

Add Camilo Romero

---

src/data.js

Add the first Lithuanian developer! 💯 😄
I've read and understood the CONTRIBUTING.
Mykolas Krupauskas

Add Mykolas Krupauskas @mykolaskrup @mkrupauskas

---

src/data.js

Adding Chris Otto Uses

---

src/data.js

Add Daryn St. Pierre

---

src/data.js

Add @ctrleffive

---

src/data.js

Please read the requirements corresponding to your pull request before you submit. You can delete this before you PR 
* Ensure your data is formatted like …

Add @mazedlx

---

src/data.js

added @jamieryandev

---

src/data.js

Added Murendeni Mukwevho

---

src/data.js

Add to data tcgumus

---

src/data.js

Add Amadeus Mader

---

src/data.js

Add Aditya Thebe Limbu

---

src/data.js

* You've read and understood the above ✅
**Add your name to verify:** Leo Melo.

Add Leo Melo

---

src/data.js

Whoops! Don’t know my own twitter handle. Sorry about that!
Jesse Dyck

Fix Jesse Dyck

---

src/data.js

Dhanish Gajjar @dhanishgajjar

---

src/data.js

**Add your name to verify:** Hans Gerwitz

Add @gerwitz

---

src/data.js

Added fidalgo

---

src/data.js

Samir Mammadhasanov @samirmh_dev

---

src/data.js

Add babasbot

---

migration.md
src/data.js

docs: add @maxpou

---

src/data.js

docs: updated Maxpou

---

src/data.js

Add Michael Rolfsen

---

src/data.js

Add @stephfh to data.js

---

src/data.js

Add Kyle McDonald to uses.tech

---

src/data.js

adds: @_raygervais

---

src/data.js

Jonesh Shrestha @shresthajonesh

---

src/data.js

Add Michael Beckwith

---

src/data.js

Jitendra Nirnejak Uses

---

src/data.js

Add Michael Herman

---

src/data.js

Add @krzysztof_zuraw

---

src/data.js

Add Esmit Perez

---

src/data.js

Add Diana G

---

src/data.js

Update data.js for Sudhanshu Bajaj @SudhanshuBajaj

---

src/data.js

Add Jeff Mair

---

src/data.js

Add @_22mahmoud

---

src/data.js

Add Bui Minh Phuc

---

src/data.js

Please read the requirements corresponding to your pull request before you submit. You can delete this before you PR 
* Ensure your data is formatted like …

Add @daankauwenberg

---

src/data.js

data.js update

---

src/data.js

Addig Gerardo Jaramillo @gerardojaras

---

src/data.js

Add @danguita

---

src/data.js

Adds Russell McWhae from Alberta, Canada

Add Russell McWhae

---

src/data.js

Add Chris Collins

---

src/data.js

Add Peter Tasker

---

src/data.js

Add Dao Chau

---

src/data.js

Add @cstrnt

---

src/data.js

Add Andrew Nguyen Vo

---

src/data.js

Add Martin Marcucci

---

src/data.js

Add @stefanjudis

---

src/data.js

* Ensure this PR has a title in the following format
* ✅ Add Your Name
* ✅ Add @twitterusername
* ✅ Add myself
* ✅ Adding myself!
* ✅ Add Your Name @twitter @github

Add Kelvin Mai

---

src/data.js

Add Maxim Zubarev

---

src/data.js

Add Marko Denic

---

src/data.js

add @hbish

---

src/data.js

Add @miku86com

---

src/data.js

Updated twitter handle

---

src/data.js

Add @BrianMitchL

---

src/data.js

Add Ryan Senn

---

src/data.js

add myself (Amirhossein Rahmati)

---

src/data.js

Add Nicholas La Roux

---

src/data.js

Add Ryan Harris, add @ryan_c_harris

---

src/data.js

Add Cabeda

---

src/data.js

added "Marko Bajlovic"

---

src/data.js

Add Aaron Uurman

---

src/data.js

Add Stan Lo

---

src/data.js

Add Jeremy Collins

---

src/data.js

Add sascha monteiro

---

src/data.js

Add Preston Lamb @prestonjlamb

---

src/data.js

Add Raul Melo

---

src/data.js

Added Jorre Spijker

---

src/data.js

Added Sythe Veenje

---

src/data.js

Forgot to add my Twitter handle
Sythe Veenje

Added @sytheveenje

---

src/data.js

Added aliahsan.tech/uses to uses

---

src/data.js

Add Ammar Alakkad

---

src/data.js

Add Lucas Schumacher

---

src/data.js

Add @GirlsCodeMK

---

src/data.js

Add @RubenJ

---

src/data.js

Add Jesse Stilwell

---

src/data.js

Add Josh Collinsworth

---

src/data.js

Hey! Was planning to be the first from NZ, but somebody beat me to it! Guess I shouldn't have waited months to update my site.
Hopefully all is in order.

Add @johnslipper

---

src/data.js

Add @jmathias

---

src/data.js

Adding myself to this (hopefully)!

Update data.js with Keith Donegan

---

src/data.js

Updated SeyhunAkyürek's profile

Updated data.js

---

src/data.js

Add Karel De Smet

---

src/data.js

Add @mffmendes

---

src/data.js

Added theanubhav.com entry

---

src/data.js

Add Chris Hufnagel

---

src/data.js

Added endormi twitter

---

src/data.js

Add Alex DUVAL

---

src/data.js

Add @mijndert

---

src/data.js

**Add your name to verify:** Eric Eggert

Add Eric Eggert (@yatil) to the site

---

src/data.js

Add Chris Jones

---

src/data.js

Adding Liam Richardson

---

src/data.js

change domain name for @siim

---

src/data.js

Add Christopher Talke

---

src/data.js

Add Duncan Bain

---

src/data.js

Add Adrián Alcorta to the /uses page

Add Adrián Alcorta Puente

---

src/data.js

Add Adil Naqvi

---

src/data.js

Add @ShayonPal

---

src/data.js

**Add your name to verify:** Gift Egwuenu

Add Gift Egwuenu @lauragift_

---

src/data.js

Add my data (Md Solaiman Hossain Rathik)

---

src/data.js

Adds Angel Taborda to data.js

---

src/data.js

Add Dan Vega

---

src/data.js

Add Yves Engetschwiler

---

src/data.js

Add Travis Luong

---

src/data.js

Add @abulkhoyer69

---

src/data.js

Add Jay Tyrrell

---

src/data.js

Add @genehack

---

src/data.js

Fix `jlozovei` uses url: remove final slash; sorry about that

Fix my own URL

---

src/data.js

Add Bryan Hickey

---

src/data.js

**I've read and understood the requirements**: YES
**My name to verify**: Sagar Soni

Add @saagarsoni

---

src/data.js

Thanks Wes Bos for this site! **You rocks!**
Ángel Guerra

Add Ángel Guerra

---

src/data.js

Add Sergio Martin

---

src/data.js

add Amir Ghaffari

---

src/data.js

Added Elio Struyf - @eliostruyf

---

src/data.js

I will take this personal website offline

Remove Daan Kauwenberg

---

src/data.js

Updated "Irshad Ali" site url

---

src/data.js

**Add your name to verify:** Yash Dave
Inspired to create on by a [DEV](https://dev.to/nickytonline/do-you-have-a-uses-page-5b82) post, awesome project!

add Yash Dave

---

src/data.js

Update Eugene Oliveros

---

src/data.js

Add Sebastien Elet

---

src/data.js

Let's add another `uses` page :). Maybe someday, someone will do something nice with all that data :D. Maybe some statistics or data analysis - it looks like a nice dataset.

Add Adam Siekierski

---

src/data.js

Adding Aymen Jarouih

---

src/data.js

Add Pablo Obando

---

src/data.js

Added Carlos Longarela profile

Update data.js with Carlos Longarela profile

---

src/data.js

Add Devansh Bajaj

---

src/data.js

Add Ali Alaa

---

src/data.js

Add @narze

---

src/data.js

Add my name Cesar Gomez

---

src/data.js

Add Erick Mwamodo

---

src/data.js

add Johannes Konings

---

src/data.js

Update: Mark Railton @railto

---

src/data.js

Add URL: https://christianoliff.com/uses/
thanks,
Christian Oliff

Add Christian Oliff

---

.gitignore
src/data.js

Add Haseeb Majid

---

src/data.js

* You've read and understood the above YES
**Add your name to verify:** LAFFONT Quentin

add Quentin Laffont

---

src/data.js

feat(src/data.js) Add Nicolas M. Pardo

---

src/data.js

Add Justin Juno

---

src/data.js

Add Gleb Skibitsky

---

src/data.js

Add @immannino

---

src/data.js

**Add your name to verify:** Soumya Ranjan Mohanty

Add @geekysrm

---

src/data.js

Add Nathan Smith

---

src/data.js

**Add your name to verify:** Dick Wyn Yong

Add @dickwyn

---

src/data.js

page is /#uses. I hope that's ok

Add Nico Bachner

---

.gitignore
src/data.js

Add @Prakhil_tp

---

src/data.js

Add Matt James

---

src/data.js

Adding Erik Hedin to data.js file.

---

src/data.js

Thanks for creating my favorite podcast @wesbos!

Add Andrew Byrd

---

src/data.js

Made a `uses` page! I read the PR reqs.

Add Patrick Tumbucon

---

src/data.js

Reverts wesbos/awesome-uses#794

Revert "Change computer for Ruben Arakelyan"

---

src/data.js

Add Matt Litzinger

---

src/data.js

Add Matt Hughes @matthughes2112

---

src/data.js

Add Rowe Morehouse

---

src/data.js

add jeffszuc

---

src/data.js

Adds juanfernandes.uk/uses

---

src/data.js

Add John Irle

---

src/data.js

Add @binakot

---

src/data.js

Added myself

---

src/data.js

Add Shubham battoo

---

src/data.js

Add @frajova

---

gatsby-node.js
src/util/stats.js

I've noticed that some people have duplicated tags (e.g. Fidalgo has Front End twice). This is causing "key prop" warnings from React when rendering the tags list in the Person component and the topics count is also affected by this showing inaccurate numbers.
This PR solves this issue.
Closes #986

Ignore duplicated tags

---

src/data.js

Added my own information on a random place in the file.

Add Simone's /uses @per5imone

---

src/data.js

Add davidak

---

.github/workflows/data-validate.yml
dangerfile.js
package-lock.json
package.json
scripts/data-validate.js
scripts/masterData.js
scripts/utils.js
src/data.js

For Issue #478
Example for how a comment would look: https://github.com/rohit-gohri/awesome-uses/pull/1#issuecomment-623158310

Use DangerJS for commenting

---

src/data.js

Remove dummy entry that got merged in #796 accidentally.
The build will pass once a bot token has been added to the project as mentioned in https://github.com/wesbos/awesome-uses/pull/796#issuecomment-707514080.

Remove invalid entry 

---

src/data.js

Add my uses

---

readme.md
src/data.js

Add @JrGiant

---

src/data.js

Add Emma Goto

---

src/data.js

Add @themisir

---

src/data.js

Add Hideki Jinnai

---

src/data.js

Add @sysrex

---

src/data.js

**Add your name to verify:** Dwayne Harris @arcatech

Add @arcatech

---

src/data.js

Add @itsmanojb

---

src/data.js

add Haryel Gillet

---

src/data.js

Add moisesnandres

---

src/data.js

Add @aguvaleriani

---

src/data.js

Add Mathias Borgmalm

---

src/data.js

Add Maxim Villivald

---

src/data.js

Add @camille_hdl

---

src/data.js

Add @httpsterio

---

src/data.js

blaise@BlaiseSebagabo

---

src/data.js

Add link to schema in data.js

---

src/data.js

Add @razbakov

---

src/data.js

Add Ale Mohamad

---

src/data.js

Add Stefan Zweifel

---

src/data.js

Adding my `uses` page on my website to the list. What a great idea!

Add EJ Mitchell

---

src/data.js

add @iamsimonsmale

---

src/data.js

Add Matthäus Mzyk

---

src/data.js

Changed my domain recently
**Add your name to verify:** Austin Gil

Updates for Austin Gil

---

src/data.js

Add @simeonGriggs

---

src/data.js

update schema link

---

src/data.js

add Marek Maras

---

src/data.js

**Add your name to verify:** Bradley Shellnut

Add Bradley Shellnut

---

readme.md
src/data.js

Pleas remove me. Thank you!
Matthäus Mzyk

Remove Matthäus Mzyk

---

readme.md
src/data.js

Add @dexterbrylle

---

src/data.js

Add @thewannabeceo

---

src/data.js

**Add your name to verify:** Seagyn Davis

Add Seagyn Davis

---

src/data.js

**Add your name to verify:** Rameez Khan

Add Rameez Khan

---

src/data.js

**Add your name to verify:** Diego López

Add Diego López

---

src/data.js

* I've read and understood the above
* My name to verify: Rosie Junghwa Yang

Add Rosie Junghwa Yang

---

src/data.js

Updating the ol’ URL

---

src/data.js

I would like to add my /uses page to the listing.

Add Matt Layman

---

src/data.js

Just started my blog, great to see so many configs and setups on a common platform!

Add @seshaljain

---

src/data.js

Add Dominik Matis

---

src/data.js

Add Gaya Kessler 

---

src/data.js

Kim Ingram @talknerdytomee

---

src/data.js

Add Alan to data.js

---

src/data.js

Add Sapan Bodiwala

---

src/data.js

Add myself to the list
**Add your name to verify:** MG Santos

Add MG Santos

---

src/data.js

change url to my german domain

---

src/data.js

**Add your name to verify:** David Levai

Update David Levai description & Twitter handle

---

src/data.js

Re-adding myself. I can tick the checkbox in the migration file if everything looks good. 🦝
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wesbos/awesome-uses/1108)

Add Niko Heikkilä

---

src/data.js

Please read the requirements corresponding to your pull request before you submit. You can delete this before you PR 
* Ensure your data is formatted like …

Add @dandevri

---

src/data.js

Add Brian Hamburg

---

src/data.js

Add Denys Tynok

---

src/data.js

**Add your name to verify:** Robin Bakker

Add Robin Bakker

---

src/data.js

updates Angel Taborda Chinea information

---

src/data.js

Add @whitep4nth3r

---

src/data.js

Add Lucas Queiroz

---

src/data.js

Add @pie_tre

---

src/data.js

**Add your name to verify:** Vic Demuzere

Add Vic Demuzere

---

src/data.js

Add Tom VanAntwerp

---

src/data.js

Remove company name from description to be more future-proof.

Update matt gregg description

---

src/data.js

**Add your name to verify:** Henrik Nyh

Add @henrik

---

src/data.js

Add alexisjanvier

---

src/data.js

Add Joshua Cerbito

---

src/data.js

Add Dušan Simić

---

src/data.js

Add @thomasjsn

---

src/data.js

Add @mnlwldr

---

src/data.js

Add @luigircruz

---

src/data.js

Add: Niels Gouman

---

src/data.js

add Samuel Wong (@desktopofsamuel)

---

src/data.js

Add Sreetam Das

---

src/data.js

Update twitter for Sam Hamburger

---

src/data.js

Update Mohammad Dohadwala

---

src/data.js

Add Shreyas Minocha

---

src/data.js

Add Zacchary Puckeridge

---

src/data.js

update site address for Maxim Villivald

---

src/data.js

Add Jonathan J. Watson - @watsonjonathanj

---

src/data.js

Fix Denys Tynok

---

src/components/Person.js
src/data.js

add Bumhan Yu (@baadaa) && fix build failure on `Person.js`

---

src/data.js

Add Joshua Ryan Velasquez

---

src/data.js

Add @simran

---

src/data.js

Add @torralbo_

---

src/data.js

Add @vista1nik

---

src/data.js

Manuel Fernandez

---

src/data.js

Update url, name and tag details

Update information @devanshbajaj

---

src/data.js

Hey Wes, thanks for maintaining the site!

Add Tobias Schmidt

---

src/data.js

Add @johanh

---

src/data.js

**Add your name to verify:** Matt Miller

Add @matt123miller 

---

src/data.js

Add Bob Matyas

---

src/data.js

Add Andrei Racasan

---

src/data.js

Add Randy Daniel @randydigital_

---

src/components/Topics.js

One can navigate through the tags using "tab" and select one by pressing "enter"
Resolves #527
Guillaume

feat: Makes tags navigable by keyboard

---

src/data.js

Add Julian Stark

---

src/data.js

✅ Add Cory Dransfeldt
✅ Add @cdransf

Add Cory Dransfeldt

---

src/data.js

Adding Manuel Coiai

---

src/data.js

Hello!
I would like to update my domain as it has recently changed.
Thanks in advance!
Best,
Patrick

UPDATE Patrick Obermeier

---

src/data.js

Add Rajanand

---

src/data.js

Add Renan Moura

---

src/data.js

add Neil Italia

---

src/data.js

Adding Marc-Andre Bombeck

---

src/data.js

Adding Bala Hantsi

---

src/data.js

Added Gavin Pereira

---

src/data.js

Add Matthew Tao

---

src/data.js

My Domain has changed recently and it was removed as part of #1309 
Re-adding with updated URL.

Re-adds Jacob Herper

---

src/data.js

Update Angelique Weger

---

src/data.js

Adding Kristina Groeger 🌸

---

src/data.js

Add Yash Singh

---

src/data.js

Sorry I made a mistake on Twitter tag.

Add @selmane_amel

---

src/data.js

Added Camilo Romero

---

src/data.js

Update Emma Goto

---

src/data.js

Adding Melanie Kat

---

src/data.js

Add Ahmed Adebisi to src/data.js
Linked Website: https://adebisiahmed.dev/uses

Add Ahmed Adebisi

---

src/data.js

Add Nathan Knowler

---

src/data.js

Update @AmmarCodes job title

---

src/data.js

Emoji was wrong, it should be Scotland, not India.
* You've read and understood the above 
**Add your name to verify:** Andy Cetnarskyj

Andy Cetnarskyj Flag Update

---

src/data.js

Add Sebastian Försth

---

src/data.js

Add Stuart McColl

---

src/data.js

- updated url
- updated description
- added twitter handle
- removed emoji
- updated tags

chore: update Nico Bachner

---

src/data.js

Add timmousk.com

---

src/data.js

Adding Harley Wilson

---

src/data.js

Pease read the requirements corresponding to your pull request before you submit. You can delete this before you PR 
* Ensure your data is formatted like other …

Chore: adding `@heyfirst_` to `/uses`

---

src/data.js

feat: add albert zhang

---

src/data.js

Add Lucas Becker

---

src/data.js

- Update Marc Littlemore role details - I now work at Netlify
- Added a trailing slash to the `/uses/` URL to avoid a redirect 😄 
Thanks!

Update Marc Littlemore details

---

src/data.js

Name: Mohamed Ouyizme
Uses: https://www.ouyiz.me/blog/uses

Add @mohouyizme

---

src/data.js

Add ln-dev on website

---

src/data.js

Typo on the twitter handle, sorry guys!

Update Stijn E.

---

src/data.js

Added Allan Im

---

src/data.js

Add Your Name

---

src/data.js

Add @sdvim

---

src/data.js

Updated Nick Reutlinger's URL to /uses

---

src/data.js

 feat: Add @itsjzt

---

src/data.js

Marko Bajlovic - @desmosthenes - added myself back again

---

src/data.js

Update Saurabh Sharma

---

src/data.js

Add @weakish

---

src/data.js

Add @MattieTK

---

src/data.js

Adding myself to this interesting project! ;-)

adding Stanislav Katkov, @5katkov

---

src/data.js

Update Diego Costa

---

src/data.js

Adding Felix Macaspac

---

src/data.js

Add @joemaffei

---

src/data.js

Adding Murendeni Mukwevho

---

src/data.js

**Add your name to verify:** Olek Baran

Update Olek Baran

---

contribution-guide.md

corrected spelling error in contribution guide

---

src/data.js

Thanks for the idea & for maintaining the repo.

Add Alex Zmn

---

src/data.js

Thank you for maintaining this! ❤️

Add Michal Kolacek

---

src/data.js

Thanks for your idea and work :)

Add Sergey Panteleev

---

src/data.js

Add https://Kieranrobson.com/uses

feat: Add Kieran Robson

---

src/data.js

Adding Paulo Regina

---

src/data.js

Updating my profile since my twitter's name account has changed from last time (it was showing a wrong favicon!). 
**Add your name to verify:** Adrián Alcorta Puente

Update Adrián Alcorta Puente

---

src/data.js

Update Tim Smith

---

src/data.js

Update Tim Leland Twitter Handle @timleland

---

src/data.js

Add Catalin Ciubotaru

---

src/data.js

Thank you for maintaining this site and accepting PRs.

Add Sal Ferrarello

---

src/data.js

Add Kyle Platt

---

src/data.js

Add Zilvinas Kucinskas

---

src/data.js

Add @syofyan_zuhad

---

src/data.js

Adding Michael Amore

---

src/data.js

Forgot the bird app!
Hammy Havoc

Added Twitter for Hammy Havoc

---

src/data.js

Add Caro Appleby

---

src/data.js

Update Muhammad Oka

---

src/data.js

Add 5am.is

---

src/data.js

Add @to1ne's /uses page pointing to https://iotcl.com/uses.

Add @to1ne

---

src/data.js

Add @sgennrw

---

src/data.js

Adding Robb Knight

---

src/data.js

Add uncenter

---

src/data.js

Add Patrick Lee

---

src/data.js

Adding Russell John

---

src/data.js

Adding Tim Teege

---

src/data.js

**Add your name to verify:** Federico Vitale

Update 'Federico Vitale'

---

src/data.js

Adding Filip Kalousek

---

src/data.js

[Adding Edimar Calebe Castanho](https://github.com/wesbos/awesome-uses/commit/2b69619b1998f8ac0f57e1f0d1ebf09c310107be)

Adding Edimar Calebe Castanho

---

src/data.js

added Dawit Mekonnen

---

src/data.js

Add Sean Boult

---

src/components/Person.js

https://user-images.githubusercontent.com/48773133/221367109-bfd9a8e8-368f-466b-a963-357553808b70.mp4
https://user-images.githubusercontent.com/48773133/221367523-c9850c4d-4fb9-4871-bc8e-56d953f8cb52.mp4

Fix scroll flickering caused by content-visibility: auto

---

contribution-guide.md

Grammar fix in contribution-guide.md

---

.github/workflows/data-validate.yml
.github/workflows/populate-readme.yml
scripts/utils.js
server.ts
src/data.js

- Updating workflows from node 13 to 16.
- Updating regex for Netlify Edge functions.
- Updating github actions with latest API.
Looks like there's still an issue with github actions
https://octokit.github.io/rest.js/v18#pulls-create-review-comment

Upgrading to node 16 for workflows, updating regex

---

src/data.js

**Add your name to verify:** Dmytro Litvinov

Add Dmytro Litvinov

---

src/data.js

Add Danny Solivan

---

src/data.js

The URL for my uses page has changed — I'm just updating it here to match the new one.

Update uses page URL for Vincent Lejtzén

---

src/data.js

Update Haseeb Majid

---

src/data.js

Add @doceazedo911

---

src/data.js

Add Angel Cruz

---

src/data.js

Hey there!
This PR adds Celso (myself) to the list!
Thanks!

Adding Celso Palmeira Neto

---

src/data.js

Adds Galen Cuthbertson profile

Add Galen Cuthbertson

---

src/data.js

Update data.js for Kim Ingram

---

src/data.js

Add ignatiusmb

---

src/data.js

Added Elmar Klausmeier

---

src/data.js

Add Jace Hensley

---

src/data.js

Add Jed Fonner

---

src/data.js

Add Ivan Santos

---

src/data.js

```ts
{
name: 'Varun Raj Manoharan',
description: 'Co Founder - Skcript, Typescript Ninja, I cook web apps, Google Developer Expert - Firebase',
url: 'https://varunraj.in/uses/',
twitter: '@zathvarun',
emoji: '🧞‍♂️',
country: '🇮🇳',
computer: 'apple',
phone: 'iphone',
tags: [
'Engineer',
'Full Stack',
'Entrepreneur',
'JavaScript',
'React',
'Developer',
'Startup',
'NextJS',
'GDE',
'Firebase'
],
}
```
Use this in case of merge conflict

 Add Varun Raj Manoharan

---

src/data.js

Add Joff Tiquez

---

src/data.js

Add @eihab_khan

---

src/data.js

Add Sho Koike

---

src/data.js

Add michaelmior

---

src/data.js

Add @devin_sharpe

---

src/data.js

I updated the information about myself.
I hope it's ok to not have an account on Twitter / X anymore.

Update Jan-Lukas Else

---

src/data.js

Just changed URL for eklausmeier.goip.de, no new entry.

Updated URL for eklausmeier.goip.de

---

src/data.js

Update Robb Knight

---

src/data.js

Add @andycarolan

---

src/data.js

Add @SarcevicAntonio

---

src/data.js

Just a few edits to my entry!
**Add your name to verify:** Salma Alam-Naylor

Update whitep4nth3r in data.js

---

readme.md
src/data.js

I recently changed domains. This PR updates my existing entry.

Update Entry for Stefan Zweifel to point to new Domain

---

src/data.js

Add Colin Ramsay

---

src/data.js

Add Earl Siachongco

---

src/data.js

Add Jose Hernandez

---

src/data.js

**Add your name to verify:** Mariusz Szubryt

Add Mariusz Szubryt

---

src/data.js

Update Emanuele Bartolesi profile

Update Emanuele Bartolesi

---

src/data.js

Add Michael Burkhardt

---

src/data.js

Add Aman Rawat

---

src/data.js

**Add your name to verify:** Marcin Dyguda

Add Marcin Dyguda

---

src/data.js

updated url and tags for John Cranston

Updated John Cranston

---

src/data.js

Add Matthew Ernisse

---

src/data.js

Add James Auble

---

src/data.js

Add Jakob Greenfeld

---

src/data.js

Another one for the pile! Thanks for maintaining this project. 🙌
**Add your name to verify:** Matt Stein

Adding Matt Stein

---

src/data.js

**Add your name to verify:** Tom MacWright

Add Tom MacWright

---

src/data.js

Adding Eric T Grubaugh

---

src/data.js

**Add your name to verify:** Guillaume Briday

Adding Guillaume Briday

---

src/data.js

Thank you for this project!
**Add your name to verify:** Jean Tinland

Add Jean Tinland

---

src/data.js

Add Stephen Bunn

---

src/data.js

Add Hector Aguilar

---

src/data.js

Add Nick Morris

---

src/data.js

Add Paul Esch-Laurent

---

src/data.js

**Add your name to verify:** Drake Bott

Add Drake Bott

---

src/data.js

changed 5am.is to petercammeraat.net

---

src/data.js

Hi there, stumbled across https://uses.tech, super cool stuff! Added myself, thanks!

Adding Morgan Gallant

---

src/data.js

Hi there, come across while searching for domain, pretty chill. Added myself, thanks.

Add Aaron Pham

---

src/data.js

Add Mike Hart

---

src/data.js

Just updating my host name here as it has changed (previous one does redirect, but that’s not ideal).

Update URL for Nathan Knowler

---

src/data.js

Adding Mike Walsh

---

src/data.js

You've read and understood the above: "Yes"
Add your name to verify: Luka Harambasic

Add Luka Harambasic

---

src/data.js

**Add your name to verify:** C Jackdaw

Add C Jackdaw

---

src/data.js

Add MITSUBOSHI Yuya

---

src/data.js

Adding Jesse Stilwell

---

src/data.js

✅ I've read and understood the requirements.
Add your name to verify: Márk Mihályi

Modify Márk Mihályi

---

src/data.js

(page is no longer active after a website redesign/relaunch)

Remove Sunny

---

src/data.js

You've read and understood the above: Yes
**Add your name to verify:** Fanis Hatzidakis

Adding Fanis Hatzidakis

---

src/data.js

Add João Vitor Zaniolo

---

src/data.js

You've read and understood the above: Yes
**Add your name to verify:** Quan Tong

Add Quan Tong

---

src/data.js

✅ You've read and understood the above
**Add your name to verify:** Imran Nazar

Add Imran Nazar

---

src/data.js

**Add your name to verify:** Thu Le

Add Thu Le

---

src/data.js

**Add your name to verify:** Amanda Parada

Add Amanda Parada

---

src/data.js

Add Gabriel Garrido

---

src/data.js

Updating URL and adding another tag

Update Diogo Moreira

---

src/data.js

Add Ruben Arakelyan

---

src/data.js

Adding Thohirah Husaini :snowman:

---

src/data.js

Add Mahesh Rijal

---

src/data.js

Switching Nic Lake social from Twitter -> Mastodon to test

---

src/components/Person.js

[URGENT][BUGFIX] Needs ( || )

---

src/data.js

**Add your name to verify:** Jeremy Ross

Add Jeremy Ross

---

src/data.js

Not sure if a Mastodon handle will work, but let's find out!
✅ You've read and understood the above
**Add your name to verify:** Jordan Hofker

Add jordan.hofker.org/uses/

---

src/data.js

Add Frank Adler

---

src/data.js

Adding Jorge Cortés

---

src/data.js

**Add your name to verify:** Marco Kamner

Add Marco Kamner

---

src/data.js

Adding Luke Davis

---

src/data.js

Updated description and URL for Mike Walsh

Mike Walsh: Update description an dURL

---

src/data.js

Adding Tim Benniks

---

src/data.js

Adding Alphan Günaydın

---

src/data.js

Add @lukeocodes

---

src/data.js

Add Rachel Cantor

---

src/data.js

Add James Harding
**Add your name to verify:** James Harding

Add James Harding

---

src/styles.css

remove flag position tweek, no longer need
from this 
to this

remove flag position tweek, no longer need

---

src/data.js

Add https://zacharykai.net/uses to uses.tech please.

Add Zachary Kai

---

src/data.js

**Add your name to verify:** Ricardo Morais

Add Ricardo Morais

---

src/data.js

You've read and understood the above
Michael Wagner

Add Michael Wagner

---

src/data.js

**Add your name to verify:** Rico van Zelst

Adding Rico van Zelst

---

src/data.js

Add journeytolunar.com/uses/

---

src/data.js

Add Bino Kochumol Varghese

---

src/data.js

Update Jovylle B's information, website link, name and twitter

---

src/data.js

Add Iago Bruno

---

src/data.js

Add Alberto Gallego

---

src/data.js

Adds a `Bluesky` account to Brad Garropy's profile, and updates some information.

Update Brad Garropy

---

src/data.js

**Add your name to verify:** Philip Van Raalte

Add Philip Van Raalte

---

src/data.js

Add Pascal Poredda

---

src/data.js

**Add your name to verify:** Charles Harwood

Add Charles Harwood

---

src/data.js

*✅ Ensure the code submitted is formatted similarly to existing code
*✅ Ensure variable, method, function, and component names are clear and concise
**Add your name to verify:** Iain Schmitt

Adding Iain Schmitt

---

src/data.js

Fix domain extension of my website (David Dias)

Update website extension for David Dias

---

src/data.js

Update data.js with adding data of @yesbhautik

---

src/data.js

Final Requirements
Add your name to verify: Thê Quach
Uses page: https://the-quach.com/uses/

Adding Thê Quach

---

src/data.js

Add your name to verify: Adam Chamberlin

Adding Adam Chamberlin

---

src/data.js

Added myself to the page, along with bluesky and mastodon links.

Add @jason@computering.pro

---

src/data.js

**Add your name to verify:** Chris Wiegman

Updating Chris Wiegman

---

src/data.js

Add Josh Corbett

---

src/data.js

**Add your name to verify:** Jack Jackson

Add Jack Jackson

---

src/data.js

Updating the information for Gabriel Kanev. :)

Updating Gabriel Kanev

---

src/data.js

✅ Add Thomas Sambruni

---

src/data.js

https://underlap.org/advent-of-blogs-reflection

Ditch bluesky

---

src/data.js

Add Shubham Singh

---

src/data.js

It's-a me.
**Add your name to verify:** Jamie Schembri

Add Jamie Schembri

---

src/data.js

**Add your name to verify:** alp1n3

Add bluesky: @alp1n3.dev

---

src/data.js

I've read and understand the rules.
- Nathan

Add Nathan Arthur

---

src/data.js

**Add your name to verify:** Chris Smith
Thanks! :)

Add Chris Smith
